# Importing Paraview

In [1]:
#conda install -c anaconda vtk

In [2]:
#pip install pyvistaqt

In [3]:
import numpy as np
import pyvista as pv
import pyvistaqt as pvqt
dataset = pv.read('C:/Users/20192167/Documents/Boeken/BEP/SU2-master/SU2-master/QuickStart/mesh_NACA0012_inv.su2')
plotter = pvqt.BackgroundPlotter()
plotter.add_mesh(dataset,show_edges=True)
plotter.view_xy(negative=False)
plotter.show_bounds()

    Surface tag  airfoil will be replaced by 1
    Surface tag  farfield will be replaced by 2


<vtkmodules.vtkRenderingAnnotation.vtkCubeAxesActor(0x000001E4AD484EA0) at 0x000001E4A7DC8CA0>

In [4]:
import pyvista as pv
pd = pv.read('C:/Users/20192167/Documents/Boeken/BEP/SU2-master/SU2-master/QuickStart/flow.vtu')
pd

UnstructuredGrid (0x1e4b058ee80)
  N Cells:	10216
  N Points:	5233
  X Bounds:	-2.000e+01, 2.000e+01
  Y Bounds:	-1.996e+01, 1.996e+01
  Z Bounds:	0.000e+00, 0.000e+00
  N Arrays:	7

In [6]:
temperature = pd['Temperature']
temperature

array([293.03778, 290.83038, 289.12076, ..., 273.13605, 273.0605 ,
       273.11478], dtype=float32)

In [11]:
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import numpy as np

import pyvista as pv
from pyvista import examples

# Define the colors we want to use
blue = np.array([12/256, 238/256, 246/256, 1])
black = np.array([11/256, 11/256, 11/256, 1])
grey = np.array([189/256, 189/256, 189/256, 1])
yellow = np.array([255/256, 247/256, 0/256, 1])
green = np.array([200/256, 247/256, 0/256, 1])
lightgreen = np.array([200/256, 247/256, 200/256, 1])
greenblue = np.array([12/256, 238/256, 200/256, 1])
darkblue = np.array([12/256, 150/256, 246/256, 1])
purple= np.array([200/256, 50/256, 246/256, 1])
pink= np.array([250/256, 50/256, 246/256, 1])
lightpink = np.array([250/256, 50/256, 246/256, 0.7])
orange = np.array([250/256, 150/256, 0/256, 0.7])
yelloworange = np.array([250/256, 200/256, 0/256, 0.7])

Temperature = np.linspace(pd['Temperature'].min(), pd['Temperature'].max(), 256)

newcolors = np.empty((256, 4))
newcolors[Temperature >= 200] = green
newcolors[Temperature > 210] = greenblue
newcolors[Temperature > 220] = blue
newcolors[Temperature > 230] = darkblue
newcolors[Temperature > 240] = purple
newcolors[Temperature > 250] = pink
newcolors[Temperature > 260] = lightpink
newcolors[Temperature > 270] = orange
newcolors[Temperature > 280] = yelloworange
newcolors[Temperature > 290] = yellow
newcolors[Temperature >= 300] = orange

my_colormap = ListedColormap(newcolors)


pl = pvqt.BackgroundPlotter()
pl.set_background('white')
pv.global_theme.font.color = 'black'
pl.add_mesh(pd, show_edges=True, line_width=0.5,scalars='Temperature',
            cmap=my_colormap,clim=[200, 300])
pl.camera_position = 'xy'
pl.show()

In [8]:
pressure = pd['Pressure']
pressure

array([130853.62, 125715.44, 123300.81, ..., 101277.69, 101210.34,
       101271.09], dtype=float32)

In [10]:
from matplotlib.colors import ListedColormap
import matplotlib.pyplot as plt
import numpy as np

import pyvista as pv
from pyvista import examples

# Define the colors we want to use
blue = np.array([12/256, 238/256, 246/256, 1])
black = np.array([11/256, 11/256, 11/256, 1])
grey = np.array([189/256, 189/256, 189/256, 1])
yellow = np.array([255/256, 247/256, 0/256, 1])
green = np.array([200/256, 247/256, 0/256, 1])
lightgreen = np.array([200/256, 247/256, 200/256, 1])
greenblue = np.array([12/256, 238/256, 200/256, 1])
darkblue = np.array([12/256, 150/256, 246/256, 1])
purple= np.array([200/256, 50/256, 246/256, 1])
pink= np.array([250/256, 50/256, 246/256, 1])
lightpink = np.array([250/256, 50/256, 246/256, 0.7])
orange = np.array([250/256, 150/256, 0/256, 0.7])
yelloworange = np.array([250/256, 200/256, 0/256, 0.7])

Pressure = np.linspace(pd['Pressure'].min(), pd['Pressure'].max(), 256)

newcolors = np.empty((256, 4))
newcolors[Pressure >= 90000] = green
newcolors[Pressure > 95000] = greenblue
newcolors[Pressure > 100000] = blue
newcolors[Pressure > 105000] = darkblue
newcolors[Pressure > 110000] = purple
newcolors[Pressure > 115000] = pink
newcolors[Pressure > 120000] = lightpink
newcolors[Pressure > 125000] = orange
newcolors[Pressure > 130000] = yelloworange
newcolors[Pressure > 135000] = yellow
newcolors[Pressure >= 140000] = orange

my_colormap = ListedColormap(newcolors)


pl = pvqt.BackgroundPlotter()
pl.set_background('white')
pv.global_theme.font.color = 'black'
pl.add_mesh(pd, show_edges=True, line_width=0.5,scalars='Pressure',
            cmap=my_colormap,clim=[9000, 14000])
pl.camera_position = 'xy'
pl.show()

In [12]:
temperature = pd['Temperature']
np.gradient(temperature, axis=None, edge_order=1)


array([-2.2073975 , -1.9585114 , -1.5203857 , ..., -0.01873779,
       -0.01063538,  0.05429077], dtype=float32)